#!/bin/bash





#chcek is a user is root
checksudo(){
            if [[ $EUID -ne 0 ]]; then
           echo "This script must be run as root" 
           echo " You need to run this script as root - run the command sudo su"
           exit 1
        fi
 }



sudo rm -r /var/lib/zerotier-one


# install libssl1.1
sudo apt install libssl1.1

# Fool script into using bookworm, got script from here 5 but edited it slightly.
# save /etc/debian-version
# (which will be something like kali-rolling)

DV_SAVE=$(cat /etc/debian_version)

# pretend we're Debian buster
echo testing | sudo tee /etc/debian_version >/dev/null

# follow ZeroTier install instructions from:
# https://www.zerotier.com/download/
# for example, if you don't care about checking gpg signatures:
curl -s https://install.zerotier.com | sudo bash

# restore /etc/debian-version
echo $DV_SAVE | sudo tee /etc/debian_version >/dev/null
